export default{
  THEME_CHANGE:"THEME_CHANGE",
  THEME_INIT:"THEME_INIT",
  POPULAR_REFRESH:"POPULAR_REFRESH",
  POPULAR_REFRESH_FAIL:"POPULAR_REFRESH_FAIL",
  POPULAR_REFERSH_SUCCESS:"POPULAR_REFERSH_SUCCESS",
  POPULAR_LOAD_MORE_SUCCESS:"POPULAR_LOAD_MORE_SUCCESS",
  POPULAR_LOAD_MORE_FAIL:"POPULAR_LOAD_MORE_FAIL",

}
